name: Release Build

on:
  push:
    tags:
      - 'v*'

env:
  BUILD_CONFIGURATION: Release
  BUILD_PLATFORM: Any CPU
  LOGFILE_VERBOSITY: diagnostic 
  
permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write
  
jobs:
  build:
    runs-on: [windows-latest]
    
    steps:
    - name: debug
      run: |
        gci env: | Format-Table -Wrap -AutoSize

    - name: checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set Up MSBuild
      uses: microsoft/setup-msbuild@v1.1

    - name: vcpkg build
      id: vcpkg
      uses: johnwason/vcpkg-action@v6
      with:
        manifest-dir: ${{ github.workspace }} # Set to directory containing vcpkg.json
        triplet: x64-windows-release
        token: ${{ github.token }}
        github-binarycache: true    
        fetch-depth: '0'

    - name: Run Build
      run: |
        msbuild /restore clrzmq4.netstandard.sln /t:build /p:Configuration=Release /v:diag

    - name: Publish NuGet Package To Local Repo
      working-directory: ./bin/release
      run: |
        echo "Publishing nuget packages"
        dotnet nuget push *.nupkg --source "https://nuget.pkg.github.com/senstar-oss" --api-key ${{ github.token }} --skip-duplicate        
        dotnet nuget push *.snupkg --source "https://nuget.pkg.github.com/senstar-oss" --api-key ${{ github.token }} --skip-duplicate        


